### ISSUE TITLE
【建议】有没有可能，合并反嘴臭和黑名单

### ISSUE THREAD

**Issue by Agnes4m** [tkgs0/nonebot-plugin-antiinsult#1]
### 功能需求

把反嘴臭的对象，列入到另外那个黑名单插件的拉黑对象里 [https://github.com/tkgs0/nonebot-plugin-blacklist](url)

### 理由

因为反嘴臭只有重启才能解除比较麻烦。。。。而且两个插件都是一个人做的应该比较容易处理吧

**Comment by tkgs0** [comment]
不是所有的"blacklist"使用者都有使用"anti-insult"的需求.
