### ISSUE TITLE
bot为管理 但是没有触发禁言

### ISSUE THREAD

**Issue by Kiana1314** [tkgs0/nonebot-plugin-antiinsult#2]
### nonebot-plugin-antiinsult 、 go-cqhttp 、 nonebot 、 Python 版本及操作系统

刚git clone的
rc4
2.0.0rc1
python 3.10.7
Windows service 2012 r2

### 列出安装的 Python 包

aiodns==3.0.0
aiofiles==0.8.0
aiohttp==3.8.3
aiosignal==1.2.0
aiosqlite==0.17.0
alembic==1.9.2
anyio==3.6.2
APScheduler==3.9.1
arrow==1.2.3
async-timeout==4.0.2
asyncpg==0.27.0
attrs==22.1.0
bbcode==1.1.0
beautifulsoup4==4.11.1
binaryornot==0.4.4
Brotli==1.0.9
cachetools==5.2.0
certifi==2022.9.24
cffi==1.15.1
chardet==5.0.0
charset-normalizer==2.1.1
chess==1.9.3
chevron==0.14.0
click==8.1.3
colorama==0.4.6
contourpy==1.0.5
cookiecutter==1.7.3
cssselect==1.1.0
cycler==0.11.0
deep-translator==1.9.0
diskcache==5.4.0
elf-rss==2.6.12
emoji==2.1.0
expandvars==0.7.0
fastapi==0.79.1
feedparser==6.0.10
fonttools==4.38.0
frozenlist==1.3.1
gino==1.0.1
greenlet==2.0.1
h11==0.14.0
h2==4.1.0
hpack==4.0.0
httpcore==0.16.3
httptools==0.5.0
httpx==0.23.1
hyperframe==6.0.1
idna==3.4
ImageHash==4.3.1
imageio==2.22.2
iso8601==1.1.0
Jinja2==3.1.2
jinja2-time==0.2.0
json5==0.9.10
kiwisolver==1.4.4
lagom==2.2.0
loguru==0.6.0
lxml==4.9.1
magneturi==1.3
Mako==1.2.4
Markdown==3.4.1
MarkupSafe==2.1.1
matplotlib==3.6.1
msgpack==1.0.4
multidict==6.0.2
nb-cli==0.6.7
nonebot-adapter-onebot==2.1.5
nonebot-plugin-alias==0.3.2
nonebot-plugin-antirecall==0.1.4
nonebot-plugin-apscheduler==0.2.0
nonebot-plugin-datastore==0.5.6
nonebot-plugin-emojimix==0.1.8
nonebot-plugin-guild-patch==0.2.1
nonebot-plugin-htmlrender==0.2.0.1
nonebot-plugin-imageutils==0.1.13.3
nonebot-plugin-localstore==0.2.0
nonebot-plugin-manager==0.5.9
nonebot-plugin-memes==0.3.9
nonebot-plugin-petpet==0.3.19
nonebot-plugin-send==0.1.3
nonebot-plugin-who-at-me==0.2.8
nonebot2==2.0.0rc1
numpy==1.23.4
opencv-python-headless==4.6.0.66
packaging==21.3
pandas==1.5.2
peewee==3.15.3
picimagesearch==3.7.3
pikpakapi==0.0.6
Pillow==9.2.0
playwright==1.27.1
poyo==0.5.0
prompt-toolkit==3.0.31
psutil==5.9.3
py-cpuinfo==8.0.0
pycares==4.2.2
pycparser==2.21
pydantic==1.9.2
pyee==9.0.4
pyfiglet==0.8.post1
Pygments==2.13.0
pygtrie==2.5.0
pymdown-extensions==9.7
pyparsing==3.0.9
pypika-tortoise==0.1.6
pyquery==1.4.3
python-dateutil==2.8.2
python-dotenv==0.21.0
python-markdown-math==0.8
python-qbittorrent==0.4.3
python-slugify==6.1.2
pytz==2022.5
pytz-deprecation-shim==0.1.0.post0
PyWavelets==1.4.1
PyYAML==6.0
requests==2.28.1
rfc3986==1.5.0
scipy==1.9.3
sgmllib3k==1.0.0
six==1.16.0
sniffio==1.3.0
soupsieve==2.3.2.post1
SQLAlchemy==1.4.41
sqlalchemy2-stubs==0.0.2a29
sqlmodel==0.0.8
starlette==0.19.1
tenacity==8.1.0
text-unidecode==1.3
tinydb==4.7.0
tomlkit==0.10.2
tortoise-orm==0.19.2
typing_extensions==4.4.0
tzdata==2022.5
tzlocal==4.2
ujson==5.5.0
urllib3==1.26.12
uvicorn==0.18.3
watchfiles==0.18.0
wcwidth==0.2.5
websockets==10.3
win32-setctime==1.1.0
yarl==1.8.1

### 如何复现

![15JL}7N3E}O )B MWWXK7O](https://user-images.githubusercontent.com/107671434/215107441-d13a45fb-6742-4d05-bb17-7f5f70c71912.jpg)

### 实际行为

禁言

**Comment by tkgs0** [comment]
"禁用飞马令" 后可触发禁言
对线模式不禁言, 禁言模式不对线 ())

**Comment by tkgs0** [comment]
需要同时触发回怼和禁言的话, 可以将 `__init__.py` 第169行的 finish 改成 send
![Screenshot_20230128_233338_com kiwibrowser browser](https://user-images.githubusercontent.com/107618388/215275438-5e9db21d-37bf-4718-9945-0d64031dcd43.jpg)

**Comment by Kiana1314** [comment]
好的 谢谢佬
