### ISSUE TITLE
不艾特机器人也能识别屏蔽词并禁言

### ISSUE THREAD

**Issue by Kiana1314** [tkgs0/nonebot-plugin-antiinsult#3]
### 功能需求

不艾特机器人也能识别屏蔽词并禁言

### 理由

群里基本没人艾特机器人才发送屏蔽词

**Comment by tkgs0** [comment]
把160行的 ` rule=to_me(), ` 去掉就行了.  
p.s. 去掉 ` rule=to_me(), ` 容易误杀
