### ISSUE TITLE
能自定义禁言时间吗

### ISSUE THREAD

**Issue by ghb010417** [tkgs0/nonebot-plugin-antiinsult#5]
### 报告清单

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我已使用最新版本测试过，确认功能并未实现。
- [X] 我确定在 [GitHub Issues](https://github.com/tkgs0/nonebot-plugin-antiinsult/issues) 中没有相同或相似的需求。
- [X] 我有足够的时间和能力，愿意为此提交 [PR](https://github.com/tkgs0/nonebot-plugin-antiinsult/pulls) 来实现功能。

### 您希望能解决什么样的问题？

不知道能不能自定义禁言时间

### 您想要的解决方案

现在一次禁言12小时有点久了，能不能自定义一次禁言的时间

**Comment by tkgs0** [comment]
月底修

**Comment by tkgs0** [comment]
已更新，可在Bot目录下的环境文件.env中添加`ANTI_INSULT_BAN_TIME`自定义禁言时长, 单位为分钟
  
示例:
```env
ANTI_INSULT_BAN_TIME=720
```
  
版本更新`0.4.0`
