### ISSUE TITLE
关键词识别遇到过长@消息或者emoji表情等消息时假死

### ISSUE THREAD

**Issue by aknyzsd** [tkgs0/nonebot-plugin-antiinsult#6]
### 报告清单

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我已使用最新版本测试过，确认问题依旧存在。
- [X] 我确定在 [GitHub Issues](https://github.com/tkgs0/nonebot-plugin-antiinsult/issues) 中没有相同或相似的问题。

### antiinsult

0.6.1

### go-cqhttp

shamrock lagran gocq号早封了

### nonebot

2.2.1

### Python

3.9

### 操作系统

win11

### 问题描述

在单个消息混合大量图片或者过长消息时，会导致nonebot正则判定卡住整个bot假死，有办法解决嘛qwq

### 复现步骤

单个消息混合大量图片或者过长消息

### 实际行为

nonebot假死

### 日志信息

一般是收到一条过长的消息

**Comment by tkgs0** [comment]
please [README](https://github.com/tkgs0/nonebot-plugin-antiinsult?tab=readme-ov-file#%EF%B8%8F-%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9), [Read it](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way), 或者我帮你算一卦

**Comment by aknyzsd** [comment]
如果是指gocq的问题的话，以上两种方式api都和gocq基本相同，而且这个应该是收到信息后的判定问题，如果一定需要gocq的话我可以去用gocq去尝试复现一下
![4f5a281cb8b796343773dc1b98f92039](https://github.com/tkgs0/nonebot-plugin-antiinsult/assets/121467598/bf3070c7-58f9-4773-a858-cc3e0d4378cb)
（拍issue之前没有截图，后来截了一张）

**Comment by aknyzsd** [comment]
gocq依然会复现如上问题
貌似找到了解决方案，但我臭学生没啥基础，佬看下？
https://github.com/kexue-z/nonebot-plugin-heweather/issues/46

**Comment by tkgs0** [comment]
> gocq依然会复现如上问题 貌似找到了解决方案，但我臭学生没啥基础，佬看下？ [kexue-z/nonebot-plugin-heweather#46](https://github.com/kexue-z/nonebot-plugin-heweather/issues/46)

未能复现该Bug
 - CPU架构: x64
 - 操作系统: Ubuntu 22.04.2 LTS x64
 - Python 3.11
 - nonebot 2.3.0
 - nonebot-adapter-onebot 2.4.3
 - go-cqhttp 
![S40623-01451456_com termux](https://github.com/tkgs0/nonebot-plugin-antiinsult/assets/107618388/2427f032-210d-4f6e-8202-e5e814790364)
1.1.0

**Comment by aknyzsd** [comment]
貌似不是本插件的问题打扰了（缝的插件有点多正在一个一测）
非常抱歉qwq

**Comment by tkgs0** [comment]
> 貌似不是本插件的问题打扰了（缝的插件有点多正在一个一测） 非常抱歉qwq

我遇到过类似的问题, 定位到一个 nonebot-plugin-word-bank2 的插件, 因为那个插件代码太多了我修不来, 所以我把它卸载了. 卸载后Bot就正常了

**Comment by aknyzsd** [comment]
并没有使用上述插件捏，不过现在先从有on_regex的插件排除对吧

**Comment by tkgs0** [comment]
> 并没有使用上述插件捏，不过现在先从有on_regex的插件排除对吧

不知道, 我也有装使用了on_regex响应器的插件, 并没有卡住

**Comment by aknyzsd** [comment]
问题解决，貌似是alconna对照片处理时出现了问题，已更新修复
