### ISSUE TITLE
新增检测文本中包含bot名称的功能

### ISSUE THREAD

**Issue by XibieTime** [tkgs0/nonebot-plugin-antiinsult#7]
### 报告清单

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我已使用最新版本测试过，确认功能并未实现。
- [X] 我确定在 [GitHub Issues](https://github.com/tkgs0/nonebot-plugin-antiinsult/issues) 中没有相同或相似的需求。
- [ ] 我有足够的时间和能力，愿意为此提交 [PR](https://github.com/tkgs0/nonebot-plugin-antiinsult/pulls) 来实现功能。

### 您希望能解决什么样的问题？

能否添加检测文本中是否包含bot名称的功能，很多人不@bot而是直接用名称辱骂，例如：“sbbot” ”这个bot是不是死了“。能否在这种情况也做出回应

### 您想要的解决方案

希望添加一段文本模糊检测的功能

**Comment by XibieTime** [comment]
已自行实现该功能（

**Comment by bangksm** [comment]
大佬，我从面包游戏插件来的，您的解答我不是很懂，能深入了解一下怎么解决我和你都出现过的问题吗

**Comment by tkgs0** [comment]
> 大佬，我从面包游戏插件来的，您的解答我不是很懂，能深入了解一下怎么解决我和你都出现过的问题吗

() 哦看错了, 不好意思

**Comment by bangksm** [comment]
> > 大佬，我从面包游戏插件来的，您的解答我不是很懂，能深入了解一下怎么解决我和你都出现过的问题吗
> 
> () 哦看错了, 不好意思

能加一下qq问一下嘛

**Comment by tkgs0** [comment]
> > > 大佬，我从面包游戏插件来的，您的解答我不是很懂，能深入了解一下怎么解决我和你都出现过的问题吗
> > 
> > 
> > () 哦看错了, 不好意思
> 
> 能加一下qq问一下嘛

你究竟想表达什么, 如果是与本插件相关的其他问题请新建一个[issue](https://github.com/tkgs0/nonebot-plugin-antiinsult/issues/new/choose), 如果是与issue发起者相关的问题请自行联系发起者, 如果以上都不是, 请参阅[提问的智慧](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way)
